# Generated by Django 4.2.7 on 2026-08-23 14:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('icon', models.CharField(help_text='Bootstrap Icon. Example: bi bi-code-slash', max_length=50, verbose_name='icon')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('additional', ckeditor.fields.RichTextField(help_text='Additional description.', verbose_name='additional')),
                ('description', ckeditor.fields.RichTextField(help_text='Describe your service.', verbose_name='description')),
            ],
            options={
                'verbose_name': '01. Services',
                'verbose_name_plural': '01. Services',
                'db_table': 'services_service',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='services_se_created_ebde2c_idx'), models.Index(fields=['status'], name='services_se_status_288ecc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField(help_text='Describe your service.', verbose_name='description')),
            ],
            options={
                'verbose_name': '01. Description',
                'verbose_name_plural': '01. Description',
                'db_table': 'services_description',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='services_de_created_55721d_idx'), models.Index(fields=['status'], name='services_de_status_0f6a09_idx')],
            },
        ),
    ]
