# Generated by Django 4.2.7 on 2026-08-08 00:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='additional',
            field=ckeditor.fields.RichTextField(help_text='Additional description.', verbose_name='Additional Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Describe your service.', verbose_name='Description'),
        ),
    ]
