# Generated by Django 6.0.7 on 2026-08-06 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('info', models.TextField(default='Copyright M.E. All Rights Reserved.', verbose_name='Info')),
                ('designed', models.CharField(max_length=150, verbose_name='Designed')),
            ],
            options={
                'verbose_name': '04. Copyright',
                'verbose_name_plural': '04. Copyright',
                'db_table': 'settings_copyright',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('tag', models.CharField(max_length=250, verbose_name='Tag')),
                ('paragraph', models.TextField(blank=True, verbose_name='Paragraph')),
            ],
            options={
                'verbose_name': '03. Footer',
                'verbose_name_plural': '03. Footer',
                'db_table': 'settings_footer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': '01. Logo',
                'verbose_name_plural': '01. Logo',
                'db_table': 'settings_logo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('icon', models.CharField(help_text='Example: fa-brands fa-facebook', max_length=100, verbose_name='Icon')),
                ('url', models.URLField(verbose_name='Url')),
            ],
            options={
                'verbose_name': '05. SocialLink',
                'verbose_name_plural': '05. SocialLink',
                'db_table': 'settings_socialLink',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menubar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='settings.menubar')),
            ],
            options={
                'verbose_name': '02. Menubar',
                'verbose_name_plural': '02. Menubar',
                'db_table': 'settings_menubar',
                'ordering': ['id'],
            },
        ),
    ]
