# Generated by Django 4.2.7 on 2026-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copyright',
            name='info',
        ),
        migrations.AddField(
            model_name='copyright',
            name='location',
            field=models.CharField(default='exit', max_length=150, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
