# Generated by Django 4.2.7 on 2026-08-23 14:21

from django.db import migrations, models
import mixins.mixing
import validation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='tag')),
                ('typed_items', models.CharField(help_text='Comma separated values. Example: Designer, Developer, Freelancer', max_length=300, verbose_name='typed_items')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/%Y/%m/%d/', validators=[validation.validators.validate_file_extension, validation.validators.validate_image_size], verbose_name='Image')),
            ],
            options={
                'verbose_name': '01. Hero',
                'verbose_name_plural': '01. Hero',
                'db_table': 'home_hero',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, mixins.mixing.StripMixin, mixins.mixing.ImageTagMixin),
        ),
    ]
