# Generated by Django 4.2.7 on 2026-08-07 11:00

import django.core.validators
from django.db import migrations, models
import mixins.mixing
import validation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('icon', models.CharField(blank=True, help_text='Enter the icon class for the stat.', max_length=100, null=True, verbose_name='Icon')),
                ('title', models.CharField(help_text='Enter the stat title.', max_length=100, verbose_name='Title')),
                ('value', models.PositiveIntegerField(default=0, help_text='Enter the stat value as a number.', validators=[django.core.validators.MinValueValidator(0, message='Value must be at least 0.'), django.core.validators.MaxValueValidator(100000, message='Value cannot exceed 100000.')], verbose_name='Value')),
            ],
            options={
                'verbose_name': '03. Stats',
                'verbose_name_plural': '03. Stats',
                'db_table': 'about_stats',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='about_stats_created_4423e0_idx'), models.Index(fields=['status'], name='about_stats_status_f2ca34_idx')],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(help_text='Enter the skill title.', max_length=100, verbose_name='Title')),
                ('value', models.PositiveIntegerField(help_text='Enter the skill value as a percentage (0-100).', validators=[django.core.validators.MinValueValidator(0, message='Value must be at least 0.'), django.core.validators.MaxValueValidator(100, message='Value cannot exceed 100.')], verbose_name='Value')),
            ],
            options={
                'verbose_name': '04. Skills',
                'verbose_name_plural': '04. Skills',
                'db_table': 'about_skills',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='about_skill_created_eb731c_idx'), models.Index(fields=['status'], name='about_skill_status_c25ae7_idx')],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text="Enter the reference's name.", max_length=100, verbose_name='Name')),
                ('position', models.CharField(blank=True, help_text="Enter the reference's position.", max_length=100, null=True, verbose_name='Position')),
                ('company', models.CharField(blank=True, help_text="Enter the reference's company.", max_length=100, null=True, verbose_name='Company')),
                ('email', models.EmailField(blank=True, help_text="Enter the reference's email.", max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text="Enter the reference's phone number.", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?\\d{10,15}$')], verbose_name='Phone')),
            ],
            options={
                'verbose_name': '06. References',
                'verbose_name_plural': '06. References',
                'db_table': 'about_references',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='about_refer_created_2a5252_idx'), models.Index(fields=['status'], name='about_refer_status_da769f_idx')],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('icon', models.CharField(blank=True, help_text='Enter the icon class for the interest.', max_length=100, null=True, verbose_name='Icon')),
                ('title', models.CharField(help_text='Enter the interest title.', max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': '05. Interests',
                'verbose_name_plural': '05. Interests',
                'db_table': 'about_interests',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='about_inter_created_afddb0_idx'), models.Index(fields=['status'], name='about_inter_status_709501_idx')],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(help_text='Enter the section title.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter the section description.', verbose_name='Description')),
            ],
            options={
                'verbose_name': '01. Description',
                'verbose_name_plural': '01. Description',
                'db_table': 'about_description',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['title'], name='about_descr_title_2dc053_idx'), models.Index(fields=['created_at'], name='about_descr_created_57fc31_idx'), models.Index(fields=['status'], name='about_descr_status_6df80d_idx')],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(help_text='Enter the title for the About Me section.', max_length=100, verbose_name='Title')),
                ('phone', models.CharField(blank=True, help_text='Valid Phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?\\d{10,15}$')], verbose_name='Phone')),
                ('email', models.EmailField(help_text='Valid email', max_length=254, verbose_name='Email')),
                ('github', models.URLField(blank=True, help_text='Github url', null=True, verbose_name='Github')),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn url', null=True, verbose_name='LinkedIn')),
                ('location', models.CharField(blank=True, help_text='Your location', max_length=100, null=True, verbose_name='Location')),
                ('education', models.CharField(blank=True, help_text='Your education', max_length=100, null=True, verbose_name='Education')),
                ('specialization', models.CharField(blank=True, help_text='Your specialization', max_length=100, null=True, verbose_name='Specialization')),
                ('experience', models.CharField(blank=True, help_text='Your experience', max_length=100, null=True, verbose_name='Experience')),
                ('availability', models.CharField(blank=True, help_text='Your availability', max_length=100, null=True, verbose_name='Availability')),
                ('image', models.ImageField(upload_to='about/', validators=[validation.validators.validate_file_extension, validation.validators.validate_image_size], verbose_name='Profile Image')),
                ('additional', models.TextField(help_text='Additional description', verbose_name='Additional Description')),
                ('description', models.TextField(help_text='Description about you', verbose_name='Description')),
            ],
            options={
                'verbose_name': '02. About Me',
                'verbose_name_plural': '02. About Me',
                'db_table': 'about_me',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='about_me_created_753c56_idx'), models.Index(fields=['status'], name='about_me_status_9a205c_idx')],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin, mixins.mixing.StripMixin),
        ),
    ]
