# Generated by Django 4.2.7 on 2026-08-23 14:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('location', models.CharField(max_length=150, verbose_name='location')),
                ('designed', models.CharField(max_length=150, verbose_name='designed')),
            ],
            options={
                'verbose_name': '04. Copyright',
                'verbose_name_plural': '04. Copyright',
                'db_table': 'settings_copyright',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('tag', models.CharField(max_length=250, verbose_name='tag')),
                ('paragraph', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='paragraph')),
            ],
            options={
                'verbose_name': '03. Footer',
                'verbose_name_plural': '03. Footer',
                'db_table': 'settings_footer',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
            options={
                'verbose_name': '01. Logo',
                'verbose_name_plural': '01. Logo',
                'db_table': 'settings_logo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('icon', models.CharField(help_text='Example: fa-brands fa-facebook', max_length=100, verbose_name='icon')),
                ('url', models.URLField(verbose_name='url')),
            ],
            options={
                'verbose_name': '05. SocialLink',
                'verbose_name_plural': '05. SocialLink',
                'db_table': 'settings_socialLink',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menubar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('url_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='url_name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='settings.menubar')),
            ],
            options={
                'verbose_name': '02. Menubar',
                'verbose_name_plural': '02. Menubar',
                'db_table': 'settings_menubar',
                'ordering': ['id'],
            },
        ),
    ]
