# Generated by Django 4.2.7 on 2026-08-08 03:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_footer_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='paragraph',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Paragraph'),
        ),
    ]
