# Generated by Django 4.2.7 on 2026-08-07 11:00

from django.db import migrations, models
import django.db.models.deletion
import mixins.mixing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(help_text='Enter the section title.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter the section description.', verbose_name='Description')),
            ],
            options={
                'verbose_name': '01. Description',
                'verbose_name_plural': '01. Description',
                'db_table': 'resume_description',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('qualification', models.CharField(max_length=255, verbose_name='Degree')),
                ('institute', models.CharField(max_length=255, verbose_name='Institution')),
                ('board', models.CharField(max_length=255, verbose_name='Board / University')),
                ('learn_start', models.DateField(verbose_name='Start Date')),
                ('learn_end', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': '03 Education',
                'verbose_name_plural': '03 Education',
                'db_table': 'resume_education',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Project Title')),
                ('description', models.TextField(help_text='Project description.', verbose_name='Description')),
            ],
            options={
                'verbose_name': '06 Project',
                'verbose_name_plural': '06 Project',
                'db_table': 'resume_project',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.CharField(help_text='Enter a brief summary.', max_length=255, verbose_name='Description')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('github', models.URLField(verbose_name='GitHub')),
                ('linkedin', models.URLField(verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': '02 Resume',
                'verbose_name_plural': '02 Resumes',
                'db_table': 'resume_resume',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('institute', models.CharField(max_length=255, verbose_name='Institute')),
                ('learn_start', models.DateField(verbose_name='Start Date')),
                ('learn_end', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('description', models.TextField(help_text='Training description.', verbose_name='Description')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='resume.resume')),
            ],
            options={
                'verbose_name': '05 Training',
                'verbose_name_plural': '05 Training',
                'db_table': 'resume_training',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('typed', models.CharField(max_length=100, verbose_name='Typed Text')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.resume')),
            ],
            options={
                'verbose_name': '04 Skills',
                'verbose_name_plural': '04 Skills',
                'db_table': 'resume_Skill',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['title'], name='resume_resu_title_78a225_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['created_at'], name='resume_resu_created_30c2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['status'], name='resume_resu_status_03d90e_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume.resume'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resume.resume'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['title'], name='resume_desc_title_c64268_idx'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['created_at'], name='resume_desc_created_2afb33_idx'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['status'], name='resume_desc_status_11c689_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['created_at'], name='resume_trai_created_e7a439_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['status'], name='resume_trai_status_c5e6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['created_at'], name='resume_Skil_created_1e487b_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['status'], name='resume_Skil_status_57ae2e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='resume_proj_created_5dcbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='resume_proj_status_007ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['created_at'], name='resume_educ_created_48ce17_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['status'], name='resume_educ_status_29b867_idx'),
        ),
    ]
