# Generated by Django 4.2.7 on 2026-08-08 00:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Enter the section description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Project description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Training description.', verbose_name='Description'),
        ),
    ]
