# Generated by Django 4.2.7 on 2026-08-23 14:24

import ckeditor.fields
from django.db import migrations, models
import mixins.mixing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='icon')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': '02. Contact Info',
                'verbose_name_plural': '02. Contact Infos',
                'db_table': 'contact_info',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(help_text='Your Email', max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('message', models.TextField(help_text='Your Messages', verbose_name='message')),
            ],
            options={
                'verbose_name': '03. Contact Me',
                'verbose_name_plural': '03. Contact Mes',
                'db_table': 'contact_me',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField(help_text='Description', verbose_name='description')),
            ],
            options={
                'verbose_name': '01. Description',
                'verbose_name_plural': '01. Descriptions',
                'db_table': 'description',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
    ]
