# Generated by Django 4.2.7 on 2026-08-08 03:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Description', verbose_name='Description'),
        ),
    ]
