# Generated by Django 4.2.7 on 2026-08-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='live_url',
            field=models.URLField(blank=True, help_text='Live project URL', max_length=500, null=True, verbose_name='live url'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='types',
            field=models.CharField(choices=[('apps', 'Apps'), ('webs', 'Webs'), ('apis', 'Apis')], default='apps', max_length=20, verbose_name='types'),
        ),
    ]
