# Generated by Django 4.2.7 on 2026-08-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('icon', models.CharField(help_text='Bootstrap Icon. Example: bi bi-code-slash', max_length=50, verbose_name='Icon')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('additional', models.TextField(help_text='Additional description.', verbose_name='Additional Description')),
                ('description', models.TextField(help_text='Describe your service.', verbose_name='Description')),
            ],
            options={
                'verbose_name': '01. Services',
                'verbose_name_plural': '01. Services',
                'db_table': 'services_service',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='services_se_created_ebde2c_idx'), models.Index(fields=['status'], name='services_se_status_288ecc_idx')],
            },
        ),
    ]
