# Generated by Django 4.2.7 on 2026-08-08 03:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_additional_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(help_text='Describe your service.', verbose_name='Description')),
            ],
            options={
                'verbose_name': '01. Description',
                'verbose_name_plural': '01. Description',
                'db_table': 'services_description',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='services_de_created_55721d_idx'), models.Index(fields=['status'], name='services_de_status_0f6a09_idx')],
            },
        ),
    ]
