# Generated by Django 6.0.7 on 2026-08-06 03:09

import django.core.validators
import mixins.mixing
import validation.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain only letters, numbers and underscore', regex='^[a-zA-Z0-9_]+$')], verbose_name='Username')),
                ('email', models.EmailField(help_text='Required. Enter a valid email address.', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(help_text='Required. Enter a valid phone number.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?\\d{10,15}$')], verbose_name='Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', validators=[validation.validators.validate_file_extension, validation.validators.validate_image_size], verbose_name='Profile Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '01. User',
                'verbose_name_plural': '01. Users',
                'db_table': 'account_users',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='account_use_created_95eac6_idx')],
            },
            bases=(mixins.mixing.StripMixin, mixins.mixing.ImageTagMixin, models.Model),
        ),
    ]
