# Generated by Django 4.2.7 on 2026-08-08 00:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_copyright_info_copyright_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='paragraph',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Paragraph'),
        ),
    ]
