# Generated by Django 4.2.7 on 2026-08-07 13:25

from django.db import migrations, models
import mixins.mixing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('types', models.CharField(choices=[('apps', 'Apps'), ('webs', 'Webs'), ('apis', 'Apis'), ('books', 'Books')], default='apps', max_length=20, verbose_name='Types')),
                ('description', models.TextField(help_text='Your description', verbose_name='Description')),
                ('image', models.FileField(upload_to='portfolio/', verbose_name='Image')),
            ],
            options={
                'verbose_name': '02 Portfolio',
                'verbose_name_plural': '02 Portfolio',
                'db_table': 'portfolio_portfolio',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='portfolio_p_created_8773bc_idx'), models.Index(fields=['status'], name='portfolio_p_status_c9d472_idx')],
            },
            bases=(models.Model, mixins.mixing.StripMixin, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(help_text='Enter the section title.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Enter the section description.', verbose_name='Description')),
            ],
            options={
                'verbose_name': '01. Description',
                'verbose_name_plural': '01. Description',
                'db_table': 'portfolio_description',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['title'], name='portfolio_d_title_21a821_idx'), models.Index(fields=['created_at'], name='portfolio_d_created_d9032d_idx'), models.Index(fields=['status'], name='portfolio_d_status_79b41b_idx')],
            },
            bases=(models.Model, mixins.mixing.StripMixin),
        ),
    ]
