# Generated by Django 4.2.7 on 2026-08-07 13:34

from django.db import migrations, models
import django.db.models.deletion
import mixins.mixing


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('image', models.FileField(upload_to='portfolio/', verbose_name='Image')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': '03 Galleries',
                'verbose_name_plural': '03 Portfolio',
                'db_table': 'portfolio_galleries',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['created_at'], name='portfolio_g_created_ea85fb_idx'), models.Index(fields=['status'], name='portfolio_g_status_dee852_idx')],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
    ]
