# Generated by Django 4.2.7 on 2026-08-08 00:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_image_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id'], 'verbose_name': '03 Galleries', 'verbose_name_plural': '03 Galleries'},
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Enter the section description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Your description', verbose_name='Description'),
        ),
    ]
